FROM node

# Defina o diretório de trabalho
WORKDIR /frontend

# Copie os arquivos necessários
COPY . .

# Instale dependências
RUN npm install

# Comando para executar o aplicativo
CMD ["node", "server.js"]

 

 


